version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Asia/Riyadh"
    open-pull-requests-limit: 5
    versioning-strategy: increase
    labels:
      - "dependencies"
      - "npm"
    groups:
      production:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
      major:
        patterns:
          - "*"
        update-types:
          - "major"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "monthly"
      time: "09:00"
      timezone: "Asia/Riyadh"
    labels:
      - "dependencies"
      - "docker"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
      time: "09:00"
      timezone: "Asia/Riyadh"
    labels:
      - "dependencies"
      - "ci"
